class Post {
  late String id, img;

  Post({required this.id, required this.img});
}

List<Post> postList = [
  Post(id: "Nika", img: "assets/images/story/image copy 2.png"),
  Post(id: "Sok", img: "assets/images/story/image copy 3.png"),
  Post(id: "Justin", img: "assets/images/story/image copy 4.png"),
  Post(id: "Ronaldo", img: "assets/images/story/image copy 5.png"),
  Post(id: "Messi", img: "assets/images/story/image copy 6.png"),
  Post(id: "souyong", img: "assets/images/story/image copy 7.png"),
  Post(id: "jjkk", img: "assets/images/story/image copy 8.png"),
  Post(id: "Dy", img: "assets/images/story/image copy 9.png"),
  Post(id: "Seng", img: "assets/images/story/image copy.png"),
  Post(id: "Dom", img: "assets/images/story/image.png"),
  Post(id: "Nika", img: "assets/images/story/image copy 2.png"),
  Post(id: "Sok", img: "assets/images/story/image copy 3.png"),
  Post(id: "Justin", img: "assets/images/story/image copy 4.png"),
  Post(id: "Ronaldo", img: "assets/images/story/image copy 5.png"),
  Post(id: "Messi", img: "assets/images/story/image copy 6.png"),
  Post(id: "souyong", img: "assets/images/story/image copy 7.png"),
  Post(id: "jjkk", img: "assets/images/story/image copy 8.png"),
  Post(id: "Dy", img: "assets/images/story/image copy 9.png"),
  Post(id: "Seng", img: "assets/images/story/image copy.png"),
  Post(id: "Dom", img: "assets/images/story/image.png"),

];

List<Post> mainPostList = [
  Post(id: "Nika", img: "assets/images/sexy/image copy 2.png"),
  Post(id: "Sok", img: "assets/images/sexy/image copy 3.png"),
  Post(id: "Justin", img: "assets/images/sexy/image copy 4.png"),
  Post(id: "Ronaldo", img: "assets/images/sexy/image copy 5.png"),
  Post(id: "Messi", img: "assets/images/sexy/image copy 6.png"),
  Post(id: "souyong", img: "assets/images/sexy/image copy 7.png"),
  Post(id: "jjkk", img: "assets/images/sexy/image copy 8.png"),
  Post(id: "Dy", img: "assets/images/sexy/image copy 9.png"),
  Post(id: "Seng", img: "assets/images/sexy/image copy 10.png"),
  Post(id: "Dom", img: "assets/images/sexy/image copy 11.png"),
  Post(id: "Nika", img: "assets/images/sexy/image copy 12.png"),
  Post(id: "Sok", img: "assets/images/sexy/image copy.png"),
  Post(id: "Justin", img: "assets/images/sexy/image copy.png"),
  Post(id: "Nika", img: "assets/images/sexy/image copy 2.png"),
  Post(id: "Sok", img: "assets/images/sexy/image copy 3.png"),
  Post(id: "Justin", img: "assets/images/sexy/image copy 4.png"),
  Post(id: "Ronaldo", img: "assets/images/sexy/image copy 5.png"),
  Post(id: "Messi", img: "assets/images/sexy/image copy 6.png"),
  Post(id: "souyong", img: "assets/images/sexy/image copy 7.png"),
  Post(id: "jjkk", img: "assets/images/sexy/image copy 8.png"),
  Post(id: "Dy", img: "assets/images/sexy/image copy 9.png"),
  Post(id: "Seng", img: "assets/images/sexy/image copy 10.png"),
  Post(id: "Dom", img: "assets/images/sexy/image copy 11.png"),
  Post(id: "Nika", img: "assets/images/sexy/image copy 12.png"),
  Post(id: "Sok", img: "assets/images/sexy/image copy.png"),
  Post(id: "Justin", img: "assets/images/sexy/image copy.png"),
  Post(id: "Nika", img: "assets/images/sexy/image copy 2.png"),
  Post(id: "Sok", img: "assets/images/sexy/image copy 3.png"),
  Post(id: "Justin", img: "assets/images/sexy/image copy 4.png"),
  Post(id: "Ronaldo", img: "assets/images/sexy/image copy 5.png"),
  Post(id: "Messi", img: "assets/images/sexy/image copy 6.png"),
  Post(id: "souyong", img: "assets/images/sexy/image copy 7.png"),
  Post(id: "jjkk", img: "assets/images/sexy/image copy 8.png"),
  Post(id: "Dy", img: "assets/images/sexy/image copy 9.png"),
  Post(id: "Seng", img: "assets/images/sexy/image copy 10.png"),
  Post(id: "Dom", img: "assets/images/sexy/image copy 11.png"),
  Post(id: "Nika", img: "assets/images/sexy/image copy 12.png"),
  Post(id: "Sok", img: "assets/images/sexy/image copy.png"),
  Post(id: "Justin", img: "assets/images/sexy/image copy.png"),
];
